import type { NavigationTree } from '@/@types/navigation'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'

// Customer Navigation
export const customerNavigation: NavigationTree[] = [
    {
        key: 'customer.dashboard',
        path: '/customer/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
    {
        key: 'customer.cylinders',
        path: '/customer/cylinders',
        title: 'My Cylinders',
        translateKey: 'nav.myCylinders',
        icon: 'myCylinders',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
    {
        key: 'customer.leaseNew',
        path: '/customer/lease-new',
        title: 'Lease New Cylinder',
        translateKey: 'nav.leaseNew',
        icon: 'leaseNew',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
    {
        key: 'customer.transactions',
        path: '/customer/transactions',
        title: 'Transaction History',
        translateKey: 'nav.transactions',
        icon: 'transactions',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
    {
        key: 'accountSection',
        path: '',
        title: 'Account',
        translateKey: 'nav.accountSection',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
    {
        key: 'customer.profile',
        path: '/customer/profile',
        title: 'My Profile',
        translateKey: 'nav.profile',
        icon: 'profile',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
    {
        key: 'customer.settings',
        path: '/customer/settings',
        title: 'Settings',
        translateKey: 'nav.settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
]

// Staff Navigation
export const staffNavigation: NavigationTree[] = [
    {
        key: 'staff.dashboard',
        path: '/staff/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['STAFF'],
        subMenu: [],
    },
    {
        key: 'staff.cylinders',
        path: '/staff/cylinders',
        title: 'Cylinders',
        translateKey: 'nav.cylinders',
        icon: 'cylinders',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['STAFF'],
        subMenu: [
            {
                key: 'staff.cylinders.all',
                path: '/staff/cylinders',
                title: 'All Cylinders',
                translateKey: 'nav.allCylinders',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
            {
                key: 'staff.cylinders.available',
                path: '/staff/cylinders?status=available',
                title: 'Available',
                translateKey: 'nav.available',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
            {
                key: 'staff.cylinders.leased',
                path: '/staff/cylinders?status=leased',
                title: 'Leased',
                translateKey: 'nav.leased',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'staff.customers',
        path: '/staff/customers',
        title: 'Customers',
        translateKey: 'nav.customers',
        icon: 'customers',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['STAFF'],
        subMenu: [],
    },
    {
        key: 'staff.leasing',
        path: '/staff/leasing',
        title: 'Leasing',
        translateKey: 'nav.leasing',
        icon: 'leasing',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['STAFF'],
        subMenu: [
            {
                key: 'staff.leasing.all',
                path: '/staff/leasing',
                title: 'All Leases',
                translateKey: 'nav.allLeases',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
            {
                key: 'staff.leasing.new',
                path: '/staff/leasing/new',
                title: 'New Lease',
                translateKey: 'nav.newLease',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
            {
                key: 'staff.leasing.returns',
                path: '/staff/leasing/returns',
                title: 'Process Return',
                translateKey: 'nav.processReturn',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'staff.swaps',
        path: '/staff/swaps',
        title: 'Cylinder Swaps',
        translateKey: 'nav.swaps',
        icon: 'swaps',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['STAFF'],
        subMenu: [
            {
                key: 'staff.swaps.all',
                path: '/staff/swaps',
                title: 'All Swaps',
                translateKey: 'nav.allSwaps',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
            {
                key: 'staff.swaps.new',
                path: '/staff/swaps/new',
                title: 'Process Swap',
                translateKey: 'nav.processSwap',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'staff.refills',
        path: '/staff/refills',
        title: 'Refills',
        translateKey: 'nav.refills',
        icon: 'refillQueue',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['STAFF'],
        subMenu: [
            {
                key: 'staff.refills.all',
                path: '/staff/refills',
                title: 'All Refills',
                translateKey: 'nav.allRefills',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
            {
                key: 'staff.refills.new',
                path: '/staff/refills/new',
                title: 'Record Refill',
                translateKey: 'nav.recordRefill',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'staff.transactions',
        path: '/staff/transactions',
        title: 'Transactions',
        translateKey: 'nav.transactions',
        icon: 'transactions',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['STAFF'],
        subMenu: [],
    },
    {
        key: 'operationsSection',
        path: '',
        title: 'Operations',
        translateKey: 'nav.operationsSection',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['STAFF'],
        subMenu: [],
    },
    {
        key: 'staff.registerCustomer',
        path: '/staff/customers/register',
        title: 'Register Customer',
        translateKey: 'nav.registerCustomer',
        icon: 'customerAdd',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['STAFF'],
        subMenu: [],
    },
]

// Operator Navigation
export const operatorNavigation: NavigationTree[] = [
    {
        key: 'operator.dashboard',
        path: '/operator/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['REFILL_OP'],
        subMenu: [],
    },
    {
        key: 'operator.refills',
        path: '/operator/refills',
        title: 'Refills',
        translateKey: 'nav.refills',
        icon: 'refillQueue',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['REFILL_OP'],
        subMenu: [
            {
                key: 'operator.refills.all',
                path: '/operator/refills',
                title: 'All Refills',
                translateKey: 'nav.allRefills',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['REFILL_OP'],
                subMenu: [],
            },
            {
                key: 'operator.refills.new',
                path: '/operator/refills/new',
                title: 'Record Refill',
                translateKey: 'nav.recordRefill',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['REFILL_OP'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'operator.swaps',
        path: '/operator/swaps',
        title: 'Cylinder Swaps',
        translateKey: 'nav.swaps',
        icon: 'swaps',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['REFILL_OP'],
        subMenu: [
            {
                key: 'operator.swaps.all',
                path: '/operator/swaps',
                title: 'All Swaps',
                translateKey: 'nav.allSwaps',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['REFILL_OP'],
                subMenu: [],
            },
            {
                key: 'operator.swaps.new',
                path: '/operator/swaps/new',
                title: 'Process Swap',
                translateKey: 'nav.processSwap',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['REFILL_OP'],
                subMenu: [],
            },
        ],
    },
]

// Admin Navigation
export const adminNavigation: NavigationTree[] = [
    {
        key: 'admin.dashboard',
        path: '/admin/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'admin.analytics',
        path: '/admin/analytics',
        title: 'Analytics',
        translateKey: 'nav.analytics',
        icon: 'analytics',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['ADMIN'],
        subMenu: [
            {
                key: 'admin.analytics.overview',
                path: '/admin/analytics',
                title: 'Overview',
                translateKey: 'nav.analyticsOverview',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'admin.analytics.revenue',
                path: '/admin/analytics/revenue',
                title: 'Revenue',
                translateKey: 'nav.revenueAnalytics',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'admin.analytics.outlets',
                path: '/admin/analytics/outlets',
                title: 'Outlet Performance',
                translateKey: 'nav.outletAnalytics',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'admin.analytics.cylinders',
                path: '/admin/analytics/cylinders',
                title: 'Cylinder Utilization',
                translateKey: 'nav.cylinderAnalytics',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'admin.analytics.customers',
                path: '/admin/analytics/customers',
                title: 'Customer Analytics',
                translateKey: 'nav.customerAnalytics',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'admin.analytics.operators',
                path: '/admin/analytics/operators',
                title: 'Operator Performance',
                translateKey: 'nav.operatorAnalytics',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'admin.reports',
        path: '/admin/reports',
        title: 'Reports',
        translateKey: 'nav.reports',
        icon: 'reports',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'managementSection',
        path: '',
        title: 'Management',
        translateKey: 'nav.managementSection',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'admin.outlets',
        path: '/admin/outlets',
        title: 'Outlets',
        translateKey: 'nav.outlets',
        icon: 'outlets',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'admin.users',
        path: '/admin/users',
        title: 'Users',
        translateKey: 'nav.users',
        icon: 'users',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'admin.registerCustomer',
        path: '/admin/customers/register',
        title: 'Register Customer',
        translateKey: 'nav.registerCustomer',
        icon: 'customerAdd',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'admin.cylinders',
        path: '/admin/cylinders',
        title: 'Cylinders',
        translateKey: 'nav.cylinders',
        icon: 'cylinders',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['ADMIN'],
        subMenu: [
            {
                key: 'admin.cylinders.all',
                path: '/admin/cylinders',
                title: 'All Cylinders',
                translateKey: 'nav.allCylinders',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'admin.cylinders.transfer',
                path: '/admin/cylinders/transfer',
                title: 'Transfer Cylinder',
                translateKey: 'nav.transferCylinder',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'admin.cylinders.scan',
                path: '/admin/cylinders/scan',
                title: 'Scan QR Code',
                translateKey: 'nav.scanQR',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'admin.leases',
        path: '/admin/leases',
        title: 'Leases',
        translateKey: 'nav.leases',
        icon: 'leasing',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['ADMIN'],
        subMenu: [
            {
                key: 'admin.leases.all',
                path: '/admin/leases',
                title: 'All Leases',
                translateKey: 'nav.allLeases',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'admin.leases.new',
                path: '/admin/leases/new',
                title: 'New Lease',
                translateKey: 'nav.newLease',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'admin.leases.return',
                path: '/admin/leases/return',
                title: 'Process Return',
                translateKey: 'nav.processReturn',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'admin.leases.overdue',
                path: '/admin/leases?status=overdue',
                title: 'Overdue Leases',
                translateKey: 'nav.overdueLeases',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'admin.refills',
        path: '/admin/refills',
        title: 'Refills',
        translateKey: 'nav.refills',
        icon: 'refillQueue',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['ADMIN'],
        subMenu: [
            {
                key: 'admin.refills.all',
                path: '/admin/refills',
                title: 'All Refills',
                translateKey: 'nav.allRefills',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'admin.refills.new',
                path: '/admin/refills/new',
                title: 'Record Refill',
                translateKey: 'nav.recordRefill',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'admin.refills.bulk',
                path: '/admin/refills/bulk',
                title: 'Bulk Refill',
                translateKey: 'nav.bulkRefill',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'admin.swaps',
        path: '/admin/swaps',
        title: 'Cylinder Swaps',
        translateKey: 'nav.swaps',
        icon: 'swaps',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['ADMIN'],
        subMenu: [
            {
                key: 'admin.swaps.all',
                path: '/admin/swaps',
                title: 'All Swaps',
                translateKey: 'nav.allSwaps',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'admin.swaps.new',
                path: '/admin/swaps/new',
                title: 'Process Swap',
                translateKey: 'nav.processSwap',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'admin.transfers',
        path: '/admin/transfers',
        title: 'Transfer History',
        translateKey: 'nav.transferHistory',
        icon: 'transfers',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'systemSection',
        path: '',
        title: 'System',
        translateKey: 'nav.systemSection',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'admin.settings',
        path: '/admin/settings/simplified',
        title: 'Settings',
        translateKey: 'nav.settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
]

// Navigation map by role
export const navigationMenuConfig = {
    customer: customerNavigation,
    staff: staffNavigation,
    refill_op: operatorNavigation,
    operator: operatorNavigation, // alias
    admin: adminNavigation,
}

// Get navigation by role
export const getNavigationByRole = (role: string): NavigationTree[] => {
    // Normalize role to lowercase and handle special cases
    let normalizedRole = role?.toLowerCase() || ''
    
    // Handle REFILL_OP vs refill_op mapping
    if (normalizedRole === 'refill_op' || normalizedRole === 'operator') {
        normalizedRole = 'refill_op'
    }
    
    console.log('[getNavigationByRole] Input role:', role, 'Normalized role:', normalizedRole)
    
    const navigation = navigationMenuConfig[
        normalizedRole as keyof typeof navigationMenuConfig
    ] || []
    
    console.log('[getNavigationByRole] Navigation items:', navigation.length)
    
    return navigation
}

// Default export for backward compatibility
const navigationConfig = adminNavigation // Default to admin navigation
export default navigationConfig
