import type { NavigationTree } from '@/@types/navigation'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'

// Customer Navigation
export const customerNavigation: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/customer/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
    {
        key: 'cylinders',
        path: '/customer/cylinders',
        title: 'My Cylinders',
        translateKey: 'nav.myCylinders',
        icon: 'myCylinders',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
    {
        key: 'leaseNew',
        path: '/customer/lease-new',
        title: 'Lease New Cylinder',
        translateKey: 'nav.leaseNew',
        icon: 'leaseNew',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
    {
        key: 'transactions',
        path: '/customer/transactions',
        title: 'Transaction History',
        translateKey: 'nav.transactions',
        icon: 'transactions',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
    {
        key: 'accountSection',
        path: '',
        title: 'Account',
        translateKey: 'nav.accountSection',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
    {
        key: 'profile',
        path: '/customer/profile',
        title: 'My Profile',
        translateKey: 'nav.profile',
        icon: 'profile',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
    {
        key: 'settings',
        path: '/customer/settings',
        title: 'Settings',
        translateKey: 'nav.settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['CUSTOMER'],
        subMenu: [],
    },
]

// Staff Navigation
export const staffNavigation: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/staff/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['STAFF'],
        subMenu: [],
    },
    {
        key: 'cylinders',
        path: '/staff/cylinders',
        title: 'Cylinders',
        translateKey: 'nav.cylinders',
        icon: 'cylinders',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['STAFF'],
        subMenu: [
            {
                key: 'allCylinders',
                path: '/staff/cylinders',
                title: 'All Cylinders',
                translateKey: 'nav.allCylinders',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
            {
                key: 'available',
                path: '/staff/cylinders?status=available',
                title: 'Available',
                translateKey: 'nav.available',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
            {
                key: 'leased',
                path: '/staff/cylinders?status=leased',
                title: 'Leased',
                translateKey: 'nav.leased',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'customers',
        path: '/staff/customers',
        title: 'Customers',
        translateKey: 'nav.customers',
        icon: 'customers',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['STAFF'],
        subMenu: [],
    },
    {
        key: 'leasing',
        path: '/staff/leasing',
        title: 'Leasing',
        translateKey: 'nav.leasing',
        icon: 'leasing',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['STAFF'],
        subMenu: [
            {
                key: 'newLease',
                path: '/staff/leasing/new',
                title: 'New Lease',
                translateKey: 'nav.newLease',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
            {
                key: 'returns',
                path: '/staff/leasing/returns',
                title: 'Process Return',
                translateKey: 'nav.processReturn',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
            {
                key: 'pending',
                path: '/staff/leasing/pending',
                title: 'Pending Requests',
                translateKey: 'nav.pendingRequests',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['STAFF'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'transactions',
        path: '/staff/transactions',
        title: 'Transactions',
        translateKey: 'nav.transactions',
        icon: 'transactions',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['STAFF'],
        subMenu: [],
    },
    {
        key: 'operationsSection',
        path: '',
        title: 'Operations',
        translateKey: 'nav.operationsSection',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['STAFF'],
        subMenu: [],
    },
    {
        key: 'inventory',
        path: '/staff/inventory',
        title: 'Inventory',
        translateKey: 'nav.inventory',
        icon: 'inventory',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['STAFF'],
        subMenu: [],
    },
    {
        key: 'reports',
        path: '/staff/reports',
        title: 'Reports',
        translateKey: 'nav.reports',
        icon: 'reports',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['STAFF'],
        subMenu: [],
    },
]

// Operator Navigation
export const operatorNavigation: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/refill-operator/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['REFILL_OP'],
        subMenu: [],
    },
    {
        key: 'refills',
        path: '/refill-operator/refills',
        title: 'Refills',
        translateKey: 'nav.refills',
        icon: 'refillQueue',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['REFILL_OP'],
        subMenu: [
            {
                key: 'allRefills',
                path: '/refill-operator/refills',
                title: 'All Refills',
                translateKey: 'nav.allRefills',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['REFILL_OP'],
                subMenu: [],
            },
            {
                key: 'newRefill',
                path: '/refill-operator/refills/new',
                title: 'Record Refill',
                translateKey: 'nav.recordRefill',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['REFILL_OP'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'qrScanner',
        path: '/refill-operator/cylinders/scan',
        title: 'QR Scanner',
        translateKey: 'nav.qrScanner',
        icon: 'qrScanner',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['REFILL_OP'],
        subMenu: [],
    },
    {
        key: 'operationsSection',
        path: '',
        title: 'Operations',
        translateKey: 'nav.operationsSection',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['REFILL_OP'],
        subMenu: [],
    },
    {
        key: 'cylinders',
        path: '/refill-operator/cylinders',
        title: 'Cylinder Status',
        translateKey: 'nav.cylinderStatus',
        icon: 'cylinderStatus',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['REFILL_OP'],
        subMenu: [],
    },
    {
        key: 'performance',
        path: '/refill-operator/performance',
        title: 'My Performance',
        translateKey: 'nav.myPerformance',
        icon: 'myPerformance',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['REFILL_OP'],
        subMenu: [],
    },
]

// Admin Navigation
export const adminNavigation: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/admin/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'analytics',
        path: '/admin/analytics',
        title: 'Analytics',
        translateKey: 'nav.analytics',
        icon: 'analytics',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['ADMIN'],
        subMenu: [
            {
                key: 'analyticsOverview',
                path: '/admin/analytics',
                title: 'Overview',
                translateKey: 'nav.analyticsOverview',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'revenueAnalytics',
                path: '/admin/analytics/revenue',
                title: 'Revenue',
                translateKey: 'nav.revenueAnalytics',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'outletAnalytics',
                path: '/admin/analytics/outlets',
                title: 'Outlet Performance',
                translateKey: 'nav.outletAnalytics',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'cylinderAnalytics',
                path: '/admin/analytics/cylinders',
                title: 'Cylinder Utilization',
                translateKey: 'nav.cylinderAnalytics',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'customerAnalytics',
                path: '/admin/analytics/customers',
                title: 'Customer Analytics',
                translateKey: 'nav.customerAnalytics',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'operatorAnalytics',
                path: '/admin/analytics/operators',
                title: 'Operator Performance',
                translateKey: 'nav.operatorAnalytics',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'managementSection',
        path: '',
        title: 'Management',
        translateKey: 'nav.managementSection',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'outlets',
        path: '/admin/outlets',
        title: 'Outlets',
        translateKey: 'nav.outlets',
        icon: 'outlets',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'users',
        path: '/admin/users',
        title: 'Users',
        translateKey: 'nav.users',
        icon: 'users',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'registerCustomer',
        path: '/admin/customers/register',
        title: 'Register Customer',
        translateKey: 'nav.registerCustomer',
        icon: 'customerAdd',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'cylinders',
        path: '/admin/cylinders',
        title: 'Cylinders',
        translateKey: 'nav.cylinders',
        icon: 'cylinders',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['ADMIN'],
        subMenu: [
            {
                key: 'allCylinders',
                path: '/admin/cylinders',
                title: 'All Cylinders',
                translateKey: 'nav.allCylinders',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'transferCylinder',
                path: '/admin/cylinders/transfer',
                title: 'Transfer Cylinder',
                translateKey: 'nav.transferCylinder',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'scanCylinder',
                path: '/admin/cylinders/scan',
                title: 'Scan QR Code',
                translateKey: 'nav.scanQR',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'leases',
        path: '/admin/leases',
        title: 'Leases',
        translateKey: 'nav.leases',
        icon: 'leasing',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['ADMIN'],
        subMenu: [
            {
                key: 'allLeases',
                path: '/admin/leases',
                title: 'All Leases',
                translateKey: 'nav.allLeases',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'newLease',
                path: '/admin/leases/new',
                title: 'New Lease',
                translateKey: 'nav.newLease',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'returnLease',
                path: '/admin/leases/return',
                title: 'Process Return',
                translateKey: 'nav.processReturn',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'overdueLeases',
                path: '/admin/leases?status=overdue',
                title: 'Overdue Leases',
                translateKey: 'nav.overdueLeases',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'refills',
        path: '/admin/refills',
        title: 'Refills',
        translateKey: 'nav.refills',
        icon: 'refillQueue',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['ADMIN'],
        subMenu: [
            {
                key: 'allRefills',
                path: '/admin/refills',
                title: 'All Refills',
                translateKey: 'nav.allRefills',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'newRefill',
                path: '/admin/refills/new',
                title: 'Record Refill',
                translateKey: 'nav.recordRefill',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
            {
                key: 'bulkRefill',
                path: '/admin/refills/bulk',
                title: 'Bulk Refill',
                translateKey: 'nav.bulkRefill',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'transfers',
        path: '/admin/transfers',
        title: 'Transfer History',
        translateKey: 'nav.transferHistory',
        icon: 'transfers',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'systemSection',
        path: '',
        title: 'System',
        translateKey: 'nav.systemSection',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'settings',
        path: '/admin/settings',
        title: 'Settings',
        translateKey: 'nav.settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'reports',
        path: '/admin/reports',
        title: 'Reports',
        translateKey: 'nav.reports',
        icon: 'reports',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
]

// Navigation map by role
export const navigationMenuConfig = {
    customer: customerNavigation,
    staff: staffNavigation,
    refill_op: operatorNavigation,
    operator: operatorNavigation, // alias
    admin: adminNavigation,
}

// Get navigation by role
export const getNavigationByRole = (role: string): NavigationTree[] => {
    // Normalize role to lowercase and handle special cases
    let normalizedRole = role?.toLowerCase() || ''
    
    // Handle REFILL_OP vs refill_op mapping
    if (normalizedRole === 'refill_op' || normalizedRole === 'operator') {
        normalizedRole = 'refill_op'
    }
    
    console.log('[getNavigationByRole] Input role:', role, 'Normalized role:', normalizedRole)
    
    const navigation = navigationMenuConfig[
        normalizedRole as keyof typeof navigationMenuConfig
    ] || []
    
    console.log('[getNavigationByRole] Navigation items:', navigation.length)
    
    return navigation
}

// Default export for backward compatibility
const navigationConfig = adminNavigation // Default to admin navigation
export default navigationConfig
