'use client'

import React, { useRef } from 'react'
import {
    PiXDuotone,
    PiDownloadDuotone,
    PiPrinterDuotone,
    PiQrCodeDuotone,
    PiCopyDuotone,
} from 'react-icons/pi'
import Button from '@/components/ui/Button'
import { toast } from 'react-hot-toast'

// New simplified interface for the modal
interface QRCodeModalProps {
    qrCode: string
    cylinderCode: string
    dataURL?: string | null  // Base64 encoded QR code image from backend
    onClose: () => void
}

// Legacy interface for backward compatibility
interface LegacyQRCodeModalProps {
    isOpen: boolean
    onClose: () => void
    cylinder: any
    qrCodeData: any | null
    isLoading: boolean
}

// New QR Code Modal component
export const QRCodeModal: React.FC<QRCodeModalProps> = ({
    qrCode,
    cylinderCode,
    dataURL,
    onClose,
}) => {
    const qrRef = useRef<HTMLDivElement>(null)

    const handleCopyCode = async () => {
        try {
            await navigator.clipboard.writeText(qrCode)
            toast.success('QR code copied to clipboard')
        } catch (error) {
            toast.error('Failed to copy QR code')
        }
    }

    const handleDownload = () => {
        if (!dataURL) {
            toast.error('QR code not available for download')
            return
        }

        // Create a canvas to add text below the QR code
        const img = new Image()
        img.onload = () => {
            const canvas = document.createElement('canvas')
            const ctx = canvas.getContext('2d')
            if (!ctx) return

            const size = 400
            const padding = 40
            const textHeight = 100
            
            canvas.width = size
            canvas.height = size + textHeight

            // White background
            ctx.fillStyle = 'white'
            ctx.fillRect(0, 0, canvas.width, canvas.height)

            // Draw the QR code image
            const qrSize = size - (padding * 2)
            ctx.drawImage(img, padding, padding, qrSize, qrSize)

            // Add cylinder code text
            ctx.fillStyle = 'black'
            ctx.font = 'bold 20px Arial'
            ctx.textAlign = 'center'
            ctx.fillText(cylinderCode, size / 2, size + 35)
            
            // Add QR code value text
            ctx.font = '14px monospace'
            ctx.fillStyle = '#666'
            ctx.fillText(qrCode, size / 2, size + 60)
            
            // Add timestamp
            ctx.font = '12px Arial'
            ctx.fillStyle = '#999'
            ctx.fillText(`Generated: ${new Date().toLocaleString()}`, size / 2, size + 85)

            // Download
            canvas.toBlob((blob) => {
                if (blob) {
                    const url = URL.createObjectURL(blob)
                    const link = document.createElement('a')
                    link.download = `${cylinderCode}-qr-code.png`
                    link.href = url
                    link.click()
                    URL.revokeObjectURL(url)
                    toast.success('QR code downloaded')
                }
            })
        }
        
        img.src = dataURL
    }

    const handlePrint = () => {
        if (!dataURL) {
            toast.error('QR code not available for printing')
            return
        }

        const printContent = `
            <div style="display: flex; flex-direction: column; align-items: center; padding: 40px; font-family: Arial, sans-serif;">
                <h2 style="margin-bottom: 20px; color: #374151;">Cylinder QR Code</h2>
                <div style="width: 300px; height: 300px; margin-bottom: 20px; padding: 10px; background: white; border: 2px solid #e5e7eb;">
                    <img src="${dataURL}" style="width: 100%; height: 100%; object-fit: contain;" alt="QR Code">
                </div>
                <p style="font-size: 20px; font-weight: bold; margin: 10px 0; color: #111827;">${cylinderCode}</p>
                <p style="font-size: 14px; color: #6b7280; font-family: monospace; word-break: break-all; max-width: 300px; text-align: center;">${qrCode}</p>
                <p style="font-size: 12px; color: #9ca3af; margin-top: 40px;">Generated by CylinderX System</p>
                <p style="font-size: 11px; color: #9ca3af;">${new Date().toLocaleString()}</p>
            </div>
        `

        const printWindow = window.open('', '_blank')
        if (printWindow) {
            printWindow.document.write(`
                <html>
                    <head>
                        <title>QR Code - ${cylinderCode}</title>
                        <style>
                            body { margin: 0; padding: 0; }
                            @media print {
                                body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                            }
                        </style>
                    </head>
                    <body>
                        ${printContent}
                    </body>
                </html>
            `)
            printWindow.document.close()
            
            // Wait for image to load before printing
            setTimeout(() => {
                printWindow.print()
                toast.success('QR code sent to printer')
            }, 500)
        }
    }

    return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-lg shadow-xl max-w-md w-full max-h-[90vh] overflow-y-auto">
                {/* Header */}
                <div className="flex items-center justify-between p-6 border-b border-gray-200">
                    <h2 className="text-xl font-semibold text-gray-900 flex items-center">
                        <PiQrCodeDuotone className="h-6 w-6 mr-2 text-blue-600" />
                        QR Code
                    </h2>
                    <button
                        onClick={onClose}
                        className="text-gray-400 hover:text-gray-600 transition-colors"
                    >
                        <PiXDuotone className="h-6 w-6" />
                    </button>
                </div>

                {/* Content */}
                <div className="p-6">
                    <div className="text-center">
                        <div className="mb-4">
                            <h3 className="text-lg font-medium text-gray-900 mb-2">
                                {cylinderCode}
                            </h3>
                            <p className="text-sm text-gray-600">
                                Scan this QR code to access cylinder information
                            </p>
                        </div>

                        {/* QR Code Display */}
                        <div 
                            ref={qrRef}
                            className="w-64 h-64 bg-gray-100 rounded-lg mx-auto mb-6 flex items-center justify-center border-2 border-gray-300 p-4"
                        >
                            {dataURL ? (
                                <img 
                                    src={dataURL} 
                                    alt="QR Code for {cylinderCode}"
                                    className="w-full h-full object-contain"
                                />
                            ) : (
                                <div className="text-center">
                                    <PiQrCodeDuotone className="h-24 w-24 text-gray-400 mx-auto mb-2" />
                                    <p className="text-sm text-gray-500">QR Code Not Available</p>
                                    <p className="text-xs text-gray-400 mt-1 font-mono break-all px-4">
                                        {qrCode}
                                    </p>
                                </div>
                            )}
                        </div>

                        {/* QR Code Value */}
                        <div className="bg-gray-50 rounded-lg p-4 mb-6">
                            <p className="text-sm text-gray-600 mb-2">QR Code Value:</p>
                            <p className="font-mono text-sm text-gray-900 break-all bg-white p-2 rounded border">
                                {qrCode}
                            </p>
                        </div>

                        {/* Action Buttons */}
                        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                            <Button
                                variant="plain"
                                size="sm"
                                onClick={handleCopyCode}
                                className="flex items-center justify-center"
                            >
                                <PiCopyDuotone className="h-4 w-4 mr-2" />
                                Copy
                            </Button>
                            <Button
                                variant="plain"
                                size="sm"
                                onClick={handleDownload}
                                className="flex items-center justify-center"
                            >
                                <PiDownloadDuotone className="h-4 w-4 mr-2" />
                                Download
                            </Button>
                            <Button
                                variant="plain"
                                size="sm"
                                onClick={handlePrint}
                                className="flex items-center justify-center"
                            >
                                <PiPrinterDuotone className="h-4 w-4 mr-2" />
                                Print
                            </Button>
                        </div>
                    </div>
                </div>

                {/* Footer */}
                <div className="bg-gray-50 px-6 py-4 rounded-b-lg">
                    <div className="flex justify-between items-center">
                        <p className="text-xs text-gray-500">
                            Generated by CylinderX System
                        </p>
                        <Button
                            variant="solid"
                            size="sm"
                            onClick={onClose}
                        >
                            Close
                        </Button>
                    </div>
                </div>
            </div>
        </div>
    )
}

// Legacy QRCodeModal component for backward compatibility
export default function LegacyQRCodeModal({
    isOpen,
    onClose,
    cylinder,
    qrCodeData,
    isLoading,
}: LegacyQRCodeModalProps) {
    if (!isOpen) return null

    // Show loading state while fetching QR code
    if (isLoading) {
        return (
            <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
                <div className="bg-white rounded-lg shadow-xl p-8">
                    <div className="flex flex-col items-center">
                        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mb-4"></div>
                        <p className="text-gray-600">Loading QR Code...</p>
                    </div>
                </div>
            </div>
        )
    }

    return (
        <QRCodeModal
            qrCode={cylinder?.qrCode || 'No QR Code'}
            cylinderCode={cylinder?.cylinderCode || cylinder?.code || `CYL-${cylinder?.id}`}
            dataURL={qrCodeData?.dataURL || null}
            onClose={onClose}
        />
    )
}